### ISSUE TITLE
No supported players installed in the system

### ISSUE THREAD

**Issue by KindCoder-no** [jijojosephk/node-sound#1]
Hi. Im trying to use the package on my macbook, but get this error when trying to run the node script. 

Works on raspberry pi

Error: 
<img width="1155" alt="Skjermbilde 2023-03-01 kl  13 32 15" src="https://user-images.githubusercontent.com/40148297/222140285-403479a1-99ca-4a70-91be-088adbb2efbc.png">

**Comment by jijojosephk** [comment]
Hi @KindCoder-no thanks for reporting the issue. This module looks for any command-line audio players in the system. And the list is predefined. I'm not using mac, so you may suggest what works on Mac. Currently the supported players are paplay, aplay.

You can see this in index.js. If you think another command should be used for mac, let me know I'll add it or you may send a pull request. I'll merge it. I'll support you the best possible way.
```
// List of supported players
const SUPPORTED_PLAYERS = [
	{
		command: 'paplay',
		handlerClass: DefaultPlayer
	},
	{
		command: 'aplay',
		handlerClass: DefaultPlayer
	}
];
```

**Comment by jijojosephk** [comment]
I think afplay is required for mac.

https://superuser.com/questions/598783/play-sound-on-mac-terminal

**Comment by jijojosephk** [comment]
Can you confirm?

**Comment by jijojosephk** [comment]
Now added afplay to the list. Can you check the new version `0.0.6`

**Comment by KindCoder-no** [comment]
I have vlc installed. And i know many systems still use it. So maybe its a good idea to implement vlc?

**Comment by jijojosephk** [comment]
Sure, can you check if the current version throws any errors?

**Comment by KindCoder-no** [comment]
Il check when im back in office. (About 30 min)

**Comment by KindCoder-no** [comment]
It works! Thanks
